// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Avatar   *string `json:"avatar,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID    string `json:"id"`
	Body  string `json:"body"`
	Likes int32  `json:"likes"`
	Views int32  `json:"views"`
}

type Query struct {
}

type User struct {
	ID     string  `json:"id"`
	Email  string  `json:"email"`
	Avatar *string `json:"avatar,omitempty"`
}
