package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/RealBirdMan91/blog/internal/graph/model"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, body *string) (*model.Post, error) {
	p, err := r.PostService.CreatePost(ctx, *body)
	if err != nil {
		return nil, err
	}

	return &model.Post{
		ID:    p.ID().String(),
		Body:  p.Body().String(),
		Likes: p.Likes().Int(),
		Views: p.Views().Int(),
	}, nil
}
